/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dividends {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Ex-Dividend date.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Amount in local currency.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    /// Adjusted dividend.
    #[serde(rename = "adjustedAmount", skip_serializing_if = "Option::is_none")]
    pub adjusted_amount: Option<f32>,
    /// Pay date.
    #[serde(rename = "payDate", skip_serializing_if = "Option::is_none")]
    pub pay_date: Option<String>,
    /// Record date.
    #[serde(rename = "recordDate", skip_serializing_if = "Option::is_none")]
    pub record_date: Option<String>,
    /// Declaration date.
    #[serde(rename = "declarationDate", skip_serializing_if = "Option::is_none")]
    pub declaration_date: Option<String>,
    /// Currency.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl Dividends {
    pub fn new() -> Dividends {
        Dividends {
            symbol: None,
            date: None,
            amount: None,
            adjusted_amount: None,
            pay_date: None,
            record_date: None,
            declaration_date: None,
            currency: None,
        }
    }
}


