/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EarningsCallTranscriptsList {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of transcripts' metadata
    #[serde(rename = "transcripts", skip_serializing_if = "Option::is_none")]
    pub transcripts: Option<Vec<crate::models::StockTranscripts>>,
}

impl EarningsCallTranscriptsList {
    pub fn new() -> EarningsCallTranscriptsList {
        EarningsCallTranscriptsList {
            symbol: None,
            transcripts: None,
        }
    }
}


