/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EarningsCalendar {
    /// Array of earnings release.
    #[serde(rename = "earningsCalendar", skip_serializing_if = "Option::is_none")]
    pub earnings_calendar: Option<Vec<crate::models::EarningRelease>>,
}

impl EarningsCalendar {
    pub fn new() -> EarningsCalendar {
        EarningsCalendar {
            earnings_calendar: None,
        }
    }
}


