/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvestmentThemes {
    /// Investment theme
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    /// Investment theme portfolio.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::InvestmentThemePortfolio>>,
}

impl InvestmentThemes {
    pub fn new() -> InvestmentThemes {
        InvestmentThemes {
            theme: None,
            data: None,
        }
    }
}


