/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PressRelease {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of major developments.
    #[serde(rename = "majorDevelopment", skip_serializing_if = "Option::is_none")]
    pub major_development: Option<Vec<crate::models::Development>>,
}

impl PressRelease {
    pub fn new() -> PressRelease {
        PressRelease {
            symbol: None,
            major_development: None,
        }
    }
}


