/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SocialSentiment {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Reddit sentiment.
    #[serde(rename = "reddit", skip_serializing_if = "Option::is_none")]
    pub reddit: Option<Vec<crate::models::RedditSentimentContent>>,
    /// Twitter sentiment.
    #[serde(rename = "twitter", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<Vec<crate::models::TwitterSentimentContent>>,
}

impl SocialSentiment {
    pub fn new() -> SocialSentiment {
        SocialSentiment {
            symbol: None,
            reddit: None,
            twitter: None,
        }
    }
}


