/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StockSymbol {
    /// Symbol description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Display symbol name.
    #[serde(rename = "displaySymbol", skip_serializing_if = "Option::is_none")]
    pub display_symbol: Option<String>,
    /// Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Security type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Primary exchange's MIC.
    #[serde(rename = "mic", skip_serializing_if = "Option::is_none")]
    pub mic: Option<String>,
    /// FIGI identifier.
    #[serde(rename = "figi", skip_serializing_if = "Option::is_none")]
    pub figi: Option<String>,
    /// Price's currency. This might be different from the reporting currency of fundamental data.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl StockSymbol {
    pub fn new() -> StockSymbol {
        StockSymbol {
            description: None,
            display_symbol: None,
            symbol: None,
            _type: None,
            mic: None,
            figi: None,
            currency: None,
        }
    }
}


